language: ruby
before_install:
- gem install image_optim_pack
script:
- git config --global user.name 'travis-deploy'
- git config --global user.email 'travis-deploy@abwesend.com'
- git remote set-url origin https://beanieboi:${GH_TOKEN}@github.com/beanieboi/weltreise.git
- ALLOW_DIRTY=1 bundle exec rake publish
branches:
  only:
  - master
env:
  global:
  - secure: h++naSiE8TlMXCERCr4nI6x4prxNUtdc2ZqT0fJSyEJbvx/9AmAeCx+6TVB4ejq0DXp2oAVqiSmTwAmNIh2Gmkgd9CquMl57gCenflaqnhZWru1HDqygnVf2BI6ypYX7IT5bMCc9EUX7yW8qRjLqmiLfl3X/V9HliJlrCkODcEZFAi5uSSXk8dDfychm1rWCf6EsNxAwLXek/IgM6uwrMjLItsA9ckW68ArUhaoG19DOx7hSDdP9HAePBrU+y6R5ev8l8yqujWeGyavdXbcNGhnCYs0KEa5ktHMPXieH0EJqSCrcpdi4KaRrjdcniAfKuBf5OJAb2WU/7fhhS4ft7blZhjLYG8gNyMv2pMaBFyABGF2n0oRslwXUPQVxyWNY4ChTdMDuu6I1c96+Hf45FLfV8G7G/nVYDau+hdL+PESIa/xcgjUJkOeSodAnpfTGYXkVlDx0Q/IxLGAflpUiVc3An4ZnuJwhQ/wNFBEwYpnLYmlUdL8Hlh3CunGW2ywCY7HfIaCaFlXLk8QMFO5MEeEyTtlhSDYQoJlgqbL+dlALws/S54AjydR8K+xp/J7TB1L+dJFQC6C/jvgGJ7vy5SigBRqRHb4o0W/CclrgmlUeDT8zni34nmGIgeoVMunV7DvzB4SX77CdczzBDs06rKIXqeg3UASKfvHyAA3rXgk=
